### ISSUE TITLE
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused. 

### ISSUE THREAD

**Issue by acgtyrant** [tuna/gdanmaku-server#13]
After installed all dependents, I run `webserver.py`, it complains at the title.

Than I use systemctl to start `redis.service`, then ` webserver.py` can execute finally, so do not omit this step in the document please.

**Comment by shartoo** [comment]
i  got the same error,but i even cannot execute  ```redis.service start ``` comand,what's wrong ?

**Comment by bigeagle** [comment]
read the documents.
