### ISSUE TITLE
解决 wechat.py 经常出问题的一个思路

### ISSUE THREAD

**Issue by berryboy2012** [tuna/gdanmaku-server#29]
如题，自带的微信端功能并没有利用到webapi的相关内容，而是直接对弹幕频道等底层对象进行操作，不仅使微信端与网页端行为不一致（如  #17 ，以及为限速机制做准备的token等），同时在修改代码时容易被遗忘（如迁移到py3.7后 #26 出现的问题 #28 ）。我觉得可以在webapi与底层操作之间加一层抽象，同时微信端不再直接操作底层对象。这样也方便以后加入其他形式的客户端支持。唯一的问题就是这工作吃力不讨好，我最近在尝试着这么做，不出意外的话这几天应该能有个大致的成品。不知道你们怎么看。PS：毕竟这是你们做的东西，我还是希望尽可能不自己岔个分支出去：）

**Comment by alick** [comment]
大胆做吧。

**Comment by jiegec** [comment]
LGTM

**Comment by berryboy2012** [comment]
https://github.com/berryboy2012/gdanmaku-server/commits/master
姑且算是有了个中间结果，以及顺路塞了个最原始的对telegram bot的支持（telegram的所有高级特性还没用到）。

**Comment by berryboy2012** [comment]
for anyone who is interested in that naive telegram implementation, here is a screenshot.
![Screenshot_20181015-153118.jpg](https://i.loli.net/2018/10/15/5bc44394f1919.jpg)

**Comment by jiegec** [comment]
赞！

**Comment by z4yx** [comment]
好厉害

**Comment by berryboy2012** [comment]
Pull request #30  merged.
