### ISSUE TITLE
企业微信的自建应用

### ISSUE THREAD

**Issue by Ealeosd123** [tuna/gdanmaku-server#31]
请问我如何通过企业微信自建的应用来发射弹幕吗？

**Comment by z4yx** [comment]
不了解企业微信的权限限制。如果可以自由的访问服务器api应该就能实现。

**Comment by Ealeosd123** [comment]
使用官方提供的WXBizMsgCrypt3来获取信息和发送信息，修改部分wechat.py的代码即可调用api，现已调试成功，谢谢
