### ISSUE TITLE
[RFE]Abstract all the config into one file

### ISSUE THREAD

**Issue by sztsian** [tuna/gdanmaku-server#7]
As this program uses redis,sqlite(right?) and WSGIServer. So there are a lot of config. But all of them are hardcoded in scripts. It is a disaster if I want to run it in OpenShift or other environment different with the hardcoded ones. So I advise this as a feature to abstract all configure into one file, then if I want to run it with other configure, I just need to change one file and it would be very easy by then.

**Comment by bigeagle** [comment]
you can put configurations in `gdanmaku/settings_local.py`, sqlite is actually not used, i will delete that line.

**Comment by alick** [comment]
closing... feel free to reopen if necessary
